### ISSUE TITLE
Others can't execute sfcli (Oracle Linux 7.4)

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#10]
```
# dir -lat /bin/sfcli
-rwxr-x--- 1 root root 403 Aug 16 00:24 /bin/sfcli
```

Installed as root user using git clone solidfire-sdk-python + python setup.py install, followed by `sudo easy_install solidfire-cli.zip`.

```
# chmod 755 /usr/bin/sfcli
# su - sfcli
Last login: Wed Aug 16 00:25:46 AEST 2017 on pts/0
$ sfcli
Traceback (most recent call last):
  File "/bin/sfcli", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Oracle Linux 7 + Python 2.7.5

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

On Ubuntu 16 which I used last night (I used pip3):

```
$ dir -lat /usr/local/bin/sfcli
-rwxr-xr-x 1 root root 328 Aug 15 11:42 /usr/local/bin/sfcli
```

**Comment by ArielCHoffman** [comment]
Hi Sean,

I was just about to respond to your other issue, but it seems you have already gleaned the problem. When you elevate to sudo to install it, you are creating the files as root. Sudo pip installing anything is an inadvisable course of action for the reasons listed here: https://stackoverflow.com/questions/33004708/osx-el-capitan-sudo-pip-install-oserror-errno-1-operation-not-permitted/33004920#33004920.

I would recommend either installing it as the user of interest or, (failing that due to permissions errors) installing it on a virtual machine.

If you are getting some kind of permissions error using regular pip install and that's the reason you elevated to sudo, it is because you have a native version of python that the OS won't allow you to change. Many OSs use older versions of python with very old packages. When you try to install the sfcli outside of a virtual environment, it tries to upgrade some of those packages and the OS stops you because it still needs the older packages. For further instructions on setting up a virtual environment, see here: https://virtualenv.pypa.io/en/stable/.

Thanks for commenting and feel free to let us know if you run into any other issues!
Ariel

**Comment by scaleoutsean** [comment]
I know sudo isn't recommended for installation and execution of 3rd party packages, but I couldn't install it any other way. 

I just tried on CentOS 7.3 - also as root - and as you can see it has different permissions. 
Perhaps it's an Oracle thing (or maybe some update in v7.4 of the OS) so we can close this.

```
# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
# which sfcli
/bin/sfcli
# dir -lat /bin/sfcli
-rwxr-xr-x. 1 root root 211 Aug 15 14:57 /bin/sfcli
# pip list | grep solidfire
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
solidfire-cli (1.4.0.339)
solidfire-sdk-python (1.4.0.271)
```
