### ISSUE TITLE
sfcli.exe account list doesn't recognize includestoragecontainers

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#4]
```
C:\Python35\Scripts>sfcli.exe account list
ERROR:element.cli.cli:list_accounts() got an unexpected keyword argument 'include_storage_containers'
```
I tried with ` --includestoragecontainers False`, same error.

(`ERROR: element.cli.cli: list_accounts()` is easier to read than `ERROR:element.cli.cli:list_accounts()`, but maybe there are other reasons why no spacing).

**Comment by ArielCHoffman** [comment]
This is an issue associated with the fact that the cli depends on the most recent version of the python sdk and you're using a slightly older version. When it is officially released on pypi, that issue will be taken care of. Thank you for looking into it though! If you want to play around with a beta version of the cli and a beta version of the sdk, you can pull them down from the new release branches or the develop branches. Otherwise, if you wait for a day or two, we'll release.

**Comment by scaleoutsean** [comment]
Got it. I was thinking it's likely a known issue, but I figured it's the same amount of work whether I first ask via email or open issue. You can close this at your convenience.

**Comment by scaleoutsean** [comment]
Verified to work fine (Debian 9.1).

* Python 2.7.13
* solidfire-cli (1.4.0.339)
* solidfire-sdk-python (1.4.0.271)
